FROM confluentinc/cp-kafka-connect-base:5.3.1
RUN  confluent-hub install --no-prompt confluentinc/kafka-connect-datagen:0.1.5
RUN  confluent-hub install --no-prompt confluentinc/kafka-connect-elasticsearch:5.3.1
